(* ¤¢¤é¤«¤¸¤á ex08_7.ml ¤òÆÉ¤ß¹ş¤ó¤Ç¤ª¤¯É¬Í×¤¢¤ê *) 
#use "ex08_7.ml" 
 
let global_ekikan_list = [ 
{kiten="Âå¡¹ÌÚ¾å¸¶"; shuten="Âå¡¹ÌÚ¸ø±à"; keiyu="ÀéÂåÅÄÀş"; kyori=1.0; jikan=2}; 
{kiten="Âå¡¹ÌÚ¸ø±à"; shuten="ÌÀ¼£¿ÀµÜÁ°"; keiyu="ÀéÂåÅÄÀş"; kyori=1.2; jikan=2}; 
{kiten="ÌÀ¼£¿ÀµÜÁ°"; shuten="É½»²Æ»"; keiyu="ÀéÂåÅÄÀş"; kyori=0.9; jikan=2}; 
{kiten="É½»²Æ»"; shuten="ÇµÌÚºä"; keiyu="ÀéÂåÅÄÀş"; kyori=1.4; jikan=3}; 
{kiten="ÇµÌÚºä"; shuten="ÀÖºä"; keiyu="ÀéÂåÅÄÀş"; kyori=1.1; jikan=2}; 
{kiten="ÀÖºä"; shuten="¹ñ²ñµÄ»öÆ²Á°"; keiyu="ÀéÂåÅÄÀş"; kyori=0.8; jikan=1}; 
{kiten="¹ñ²ñµÄ»öÆ²Á°"; shuten="²â¥ö´Ø"; keiyu="ÀéÂåÅÄÀş"; kyori=0.7; jikan=1}; 
{kiten="²â¥ö´Ø"; shuten="ÆüÈæÃ«"; keiyu="ÀéÂåÅÄÀş"; kyori=1.2; jikan=2}; 
{kiten="ÆüÈæÃ«"; shuten="Æó½Å¶¶Á°"; keiyu="ÀéÂåÅÄÀş"; kyori=0.7; jikan=1}; 
{kiten="Æó½Å¶¶Á°"; shuten="Âç¼êÄ®"; keiyu="ÀéÂåÅÄÀş"; kyori=0.7; jikan=1}; 
{kiten="Âç¼êÄ®"; shuten="¿·¸æÃã¥Î¿å"; keiyu="ÀéÂåÅÄÀş"; kyori=1.3; jikan=2}; 
{kiten="¿·¸æÃã¥Î¿å"; shuten="ÅòÅç"; keiyu="ÀéÂåÅÄÀş"; kyori=1.2; jikan=2}; 
{kiten="ÅòÅç"; shuten="º¬ÄÅ"; keiyu="ÀéÂåÅÄÀş"; kyori=1.2; jikan=2}; 
{kiten="º¬ÄÅ"; shuten="ÀéÂÌÌÚ"; keiyu="ÀéÂåÅÄÀş"; kyori=1.0; jikan=2}; 
{kiten="ÀéÂÌÌÚ"; shuten="À¾ÆüÊëÎ¤"; keiyu="ÀéÂåÅÄÀş"; kyori=0.9; jikan=1}; 
{kiten="À¾ÆüÊëÎ¤"; shuten="Ä®²°"; keiyu="ÀéÂåÅÄÀş"; kyori=1.7; jikan=2}; 
{kiten="Ä®²°"; shuten="ËÌÀé½»"; keiyu="ÀéÂåÅÄÀş"; kyori=2.6; jikan=3}; 
{kiten="ËÌÀé½»"; shuten="°½À¥"; keiyu="ÀéÂåÅÄÀş"; kyori=2.5; jikan=3}; 
{kiten="°½À¥"; shuten="ËÌ°½À¥"; keiyu="ÀéÂåÅÄÀş"; kyori=2.1; jikan=4}; 
{kiten="ÀõÁğ"; shuten="ÅÄ¸¶Ä®"; keiyu="¶äºÂÀş"; kyori=0.8; jikan=2}; 
{kiten="ÅÄ¸¶Ä®"; shuten="°ğ²ÙÄ®"; keiyu="¶äºÂÀş"; kyori=0.7; jikan=1}; 
{kiten="°ğ²ÙÄ®"; shuten="¾åÌî"; keiyu="¶äºÂÀş"; kyori=0.7; jikan=2}; 
{kiten="¾åÌî"; shuten="¾åÌî¹­¾®Ï©"; keiyu="¶äºÂÀş"; kyori=0.5; jikan=2}; 
{kiten="¾åÌî¹­¾®Ï©"; shuten="Ëö¹­Ä®"; keiyu="¶äºÂÀş"; kyori=0.6; jikan=1}; 
{kiten="Ëö¹­Ä®"; shuten="¿ÀÅÄ"; keiyu="¶äºÂÀş"; kyori=1.1; jikan=2}; 
{kiten="¿ÀÅÄ"; shuten="»°±ÛÁ°"; keiyu="¶äºÂÀş"; kyori=0.7; jikan=1}; 
{kiten="»°±ÛÁ°"; shuten="ÆüËÜ¶¶"; keiyu="¶äºÂÀş"; kyori=0.6; jikan=2}; 
{kiten="ÆüËÜ¶¶"; shuten="µş¶¶"; keiyu="¶äºÂÀş"; kyori=0.7; jikan=2}; 
{kiten="µş¶¶"; shuten="¶äºÂ"; keiyu="¶äºÂÀş"; kyori=0.7; jikan=1}; 
{kiten="¶äºÂ"; shuten="¿·¶¶"; keiyu="¶äºÂÀş"; kyori=0.9; jikan=2}; 
{kiten="¿·¶¶"; shuten="¸×¥ÎÌç"; keiyu="¶äºÂÀş"; kyori=0.8; jikan=2}; 
{kiten="¸×¥ÎÌç"; shuten="Î¯ÃÓ»³²¦"; keiyu="¶äºÂÀş"; kyori=0.6; jikan=2}; 
{kiten="Î¯ÃÓ»³²¦"; shuten="ÀÖºä¸«Éí"; keiyu="¶äºÂÀş"; kyori=0.9; jikan=2}; 
{kiten="ÀÖºä¸«Éí"; shuten="ÀÄ»³°ìÃúÌÜ"; keiyu="¶äºÂÀş"; kyori=1.3; jikan=2}; 
{kiten="ÀÄ»³°ìÃúÌÜ"; shuten="³°±ñÁ°"; keiyu="¶äºÂÀş"; kyori=0.7; jikan=2}; 
{kiten="³°±ñÁ°"; shuten="É½»²Æ»"; keiyu="¶äºÂÀş"; kyori=0.7; jikan=1}; 
{kiten="É½»²Æ»"; shuten="½ÂÃ«"; keiyu="¶äºÂÀş"; kyori=1.3; jikan=1}; 
{kiten="½ÂÃ«"; shuten="É½»²Æ»"; keiyu="È¾Â¢ÌçÀş"; kyori=1.3; jikan=2}; 
{kiten="É½»²Æ»"; shuten="ÀÄ»³°ìÃúÌÜ"; keiyu="È¾Â¢ÌçÀş"; kyori=1.4; jikan=2}; 
{kiten="ÀÄ»³°ìÃúÌÜ"; shuten="±ÊÅÄÄ®"; keiyu="È¾Â¢ÌçÀş"; kyori=1.3; jikan=2}; 
{kiten="±ÊÅÄÄ®"; shuten="È¾Â¢Ìç"; keiyu="È¾Â¢ÌçÀş"; kyori=1.0; jikan=2}; 
{kiten="È¾Â¢Ìç"; shuten="¶åÃÊ²¼"; keiyu="È¾Â¢ÌçÀş"; kyori=1.6; jikan=2}; 
{kiten="¶åÃÊ²¼"; shuten="¿ÀÊİÄ®"; keiyu="È¾Â¢ÌçÀş"; kyori=0.4; jikan=1}; 
{kiten="¿ÀÊİÄ®"; shuten="Âç¼êÄ®"; keiyu="È¾Â¢ÌçÀş"; kyori=1.7; jikan=3}; 
{kiten="Âç¼êÄ®"; shuten="»°±ÛÁ°"; keiyu="È¾Â¢ÌçÀş"; kyori=0.7; jikan=1}; 
{kiten="»°±ÛÁ°"; shuten="¿åÅ·µÜÁ°"; keiyu="È¾Â¢ÌçÀş"; kyori=1.3; jikan=2}; 
{kiten="¿åÅ·µÜÁ°"; shuten="À¶À¡Çò²Ï"; keiyu="È¾Â¢ÌçÀş"; kyori=1.7; jikan=3}; 
{kiten="À¶À¡Çò²Ï"; shuten="½»µÈ"; keiyu="È¾Â¢ÌçÀş"; kyori=1.9; jikan=3}; 
{kiten="½»µÈ"; shuten="¶Ó»åÄ®"; keiyu="È¾Â¢ÌçÀş"; kyori=1.; jikan=2}; 
{kiten="¶Ó»åÄ®"; shuten="²¡¾å"; keiyu="È¾Â¢ÌçÀş"; kyori=1.4; jikan=2}; 
{kiten="ÃæÌÜ¹õ"; shuten="·ÃÈæ¼÷"; keiyu="ÆüÈæÃ«Àş"; kyori=1.; jikan=2}; 
{kiten="·ÃÈæ¼÷"; shuten="¹­Èø"; keiyu="ÆüÈæÃ«Àş"; kyori=1.5; jikan=3}; 
{kiten="¹­Èø"; shuten="Ï»ËÜÌÚ"; keiyu="ÆüÈæÃ«Àş"; kyori=1.7; jikan=3}; 
{kiten="Ï»ËÜÌÚ"; shuten="¿ÀÃ«Ä®"; keiyu="ÆüÈæÃ«Àş"; kyori=1.5; jikan=3}; 
{kiten="¿ÀÃ«Ä®"; shuten="²â¥ö´Ø"; keiyu="ÆüÈæÃ«Àş"; kyori=1.3; jikan=2}; 
{kiten="²â¥ö´Ø"; shuten="ÆüÈæÃ«"; keiyu="ÆüÈæÃ«Àş"; kyori=1.2; jikan=2}; 
{kiten="ÆüÈæÃ«"; shuten="¶äºÂ"; keiyu="ÆüÈæÃ«Àş"; kyori=0.4; jikan=1}; 
{kiten="¶äºÂ"; shuten="Åì¶äºÂ"; keiyu="ÆüÈæÃ«Àş"; kyori=0.4; jikan=1}; 
{kiten="Åì¶äºÂ"; shuten="ÃÛÃÏ"; keiyu="ÆüÈæÃ«Àş"; kyori=0.6; jikan=2}; 
{kiten="ÃÛÃÏ"; shuten="È¬ÃúËÙ"; keiyu="ÆüÈæÃ«Àş"; kyori=1.; jikan=2}; 
{kiten="È¬ÃúËÙ"; shuten="³ı¾ìÄ®"; keiyu="ÆüÈæÃ«Àş"; kyori=0.5; jikan=1}; 
{kiten="³ı¾ìÄ®"; shuten="¿Í·ÁÄ®"; keiyu="ÆüÈæÃ«Àş"; kyori=0.9; jikan=2}; 
{kiten="¿Í·ÁÄ®"; shuten="¾®ÅÁÇÏÄ®"; keiyu="ÆüÈæÃ«Àş"; kyori=0.6; jikan=1}; 
{kiten="¾®ÅÁÇÏÄ®"; shuten="½©ÍÕ¸¶"; keiyu="ÆüÈæÃ«Àş"; kyori=0.9; jikan=2}; 
{kiten="½©ÍÕ¸¶"; shuten="Ãç¸æÅÌÄ®"; keiyu="ÆüÈæÃ«Àş"; kyori=1.; jikan=1}; 
{kiten="Ãç¸æÅÌÄ®"; shuten="¾åÌî"; keiyu="ÆüÈæÃ«Àş"; kyori=0.5; jikan=1}; 
{kiten="¾åÌî"; shuten="ÆşÃ«"; keiyu="ÆüÈæÃ«Àş"; kyori=1.2; jikan=2}; 
{kiten="ÆşÃ«"; shuten="»°¥ÎÎØ"; keiyu="ÆüÈæÃ«Àş"; kyori=1.2; jikan=2}; 
{kiten="»°¥ÎÎØ"; shuten="ÆîÀé½»"; keiyu="ÆüÈæÃ«Àş"; kyori=0.8; jikan=2}; 
{kiten="ÆîÀé½»"; shuten="ËÌÀé½»"; keiyu="ÆüÈæÃ«Àş"; kyori=1.8; jikan=3}; 
{kiten="ÃÓÂŞ"; shuten="¿·ÂçÄÍ"; keiyu="´İ¥ÎÆâÀş"; kyori=1.8; jikan=3}; 
{kiten="¿·ÂçÄÍ"; shuten="è¬²ÙÃ«"; keiyu="´İ¥ÎÆâÀş"; kyori=1.2; jikan=2}; 
{kiten="è¬²ÙÃ«"; shuten="¸å³Ú±à"; keiyu="´İ¥ÎÆâÀş"; kyori=1.8; jikan=2}; 
{kiten="¸å³Ú±à"; shuten="ËÜ¶¿»°ÃúÌÜ"; keiyu="´İ¥ÎÆâÀş"; kyori=0.8; jikan=1}; 
{kiten="ËÜ¶¿»°ÃúÌÜ"; shuten="¸æÃã¥Î¿å"; keiyu="´İ¥ÎÆâÀş"; kyori=0.8; jikan=1}; 
{kiten="¸æÃã¥Î¿å"; shuten="Ã¸Ï©Ä®"; keiyu="´İ¥ÎÆâÀş"; kyori=0.8; jikan=1}; 
{kiten="Ã¸Ï©Ä®"; shuten="Âç¼êÄ®"; keiyu="´İ¥ÎÆâÀş"; kyori=0.9; jikan=2}; 
{kiten="Âç¼êÄ®"; shuten="Åìµş"; keiyu="´İ¥ÎÆâÀş"; kyori=0.6; jikan=1}; 
{kiten="Åìµş"; shuten="¶äºÂ"; keiyu="´İ¥ÎÆâÀş"; kyori=1.1; jikan=2}; 
{kiten="¶äºÂ"; shuten="²â¥ö´Ø"; keiyu="´İ¥ÎÆâÀş"; kyori=1.0; jikan=2}; 
{kiten="²â¥ö´Ø"; shuten="¹ñ²ñµÄ»öÆ²Á°"; keiyu="´İ¥ÎÆâÀş"; kyori=0.7; jikan=1}; 
{kiten="¹ñ²ñµÄ»öÆ²Á°"; shuten="ÀÖºä¸«Éí"; keiyu="´İ¥ÎÆâÀş"; kyori=0.9; jikan=2}; 
{kiten="ÀÖºä¸«Éí"; shuten="»Í¥ÄÃ«"; keiyu="´İ¥ÎÆâÀş"; kyori=1.3; jikan=2}; 
{kiten="»Í¥ÄÃ«"; shuten="»ÍÃ«»°ÃúÌÜ"; keiyu="´İ¥ÎÆâÀş"; kyori=1.0; jikan=2}; 
{kiten="»ÍÃ«»°ÃúÌÜ"; shuten="¿·½É¸æ±ñÁ°"; keiyu="´İ¥ÎÆâÀş"; kyori=0.9; jikan=1}; 
{kiten="¿·½É¸æ±ñÁ°"; shuten="¿·½É»°ÃúÌÜ"; keiyu="´İ¥ÎÆâÀş"; kyori=0.7; jikan=1}; 
{kiten="¿·½É»°ÃúÌÜ"; shuten="¿·½É"; keiyu="´İ¥ÎÆâÀş"; kyori=0.3; jikan=1}; 
{kiten="¿·½É"; shuten="À¾¿·½É"; keiyu="´İ¥ÎÆâÀş"; kyori=0.8; jikan=1}; 
{kiten="À¾¿·½É"; shuten="ÃæÌîºä¾å"; keiyu="´İ¥ÎÆâÀş"; kyori=1.1; jikan=2}; 
{kiten="ÃæÌîºä¾å"; shuten="¿·ÃæÌî"; keiyu="´İ¥ÎÆâÀş"; kyori=1.1; jikan=2}; 
{kiten="¿·ÃæÌî"; shuten="Åì¹â±ß»û"; keiyu="´İ¥ÎÆâÀş"; kyori=1.0; jikan=1}; 
{kiten="Åì¹â±ß»û"; shuten="¿·¹â±ß»û"; keiyu="´İ¥ÎÆâÀş"; kyori=0.9; jikan=1}; 
{kiten="¿·¹â±ß»û"; shuten="Æî°¤º´¥öÃ«"; keiyu="´İ¥ÎÆâÀş"; kyori=1.2; jikan=2}; 
{kiten="Æî°¤º´¥öÃ«"; shuten="²®·¦"; keiyu="´İ¥ÎÆâÀş"; kyori=1.5; jikan=2}; 
{kiten="ÃæÌîºä¾å"; shuten="ÃæÌî¿·¶¶"; keiyu="´İ¥ÎÆâÀş"; kyori=1.3; jikan=2}; 
{kiten="ÃæÌî¿·¶¶"; shuten="ÃæÌîÉÙ»Î¸«Ä®"; keiyu="´İ¥ÎÆâÀş"; kyori=0.6; jikan=1}; 
{kiten="ÃæÌîÉÙ»Î¸«Ä®"; shuten="ÊıÆîÄ®"; keiyu="´İ¥ÎÆâÀş"; kyori=1.3; jikan=2}; 
{kiten="»Ô¥öÃ«"; shuten="»Í¥ÄÃ«"; keiyu="ÆîËÌÀş"; kyori=1.0; jikan=2}; 
{kiten="»Í¥ÄÃ«"; shuten="±ÊÅÄÄ®"; keiyu="ÆîËÌÀş"; kyori=1.3; jikan=3}; 
{kiten="±ÊÅÄÄ®"; shuten="Î¯ÃÓ»³²¦"; keiyu="ÆîËÌÀş"; kyori=0.9; jikan=1}; 
{kiten="Î¯ÃÓ»³²¦"; shuten="Ï»ËÜÌÚ°ìÃúÌÜ"; keiyu="ÆîËÌÀş"; kyori=0.9; jikan=2}; 
{kiten="Ï»ËÜÌÚ°ìÃúÌÜ"; shuten="ËãÉÛ½½ÈÖ"; keiyu="ÆîËÌÀş"; kyori=1.2; jikan=2}; 
{kiten="ËãÉÛ½½ÈÖ"; shuten="Çò¶â¹âÎØ"; keiyu="ÆîËÌÀş"; kyori=1.3; jikan=2}; 
{kiten="Çò¶â¹âÎØ"; shuten="Çò¶âÂæ"; keiyu="ÆîËÌÀş"; kyori=1.0; jikan=2}; 
{kiten="Çò¶âÂæ"; shuten="ÌÜ¹õ"; keiyu="ÆîËÌÀş"; kyori=1.3; jikan=2}; 
{kiten="»Ô¥öÃ«"; shuten="ÈÓÅÄ¶¶"; keiyu="ÆîËÌÀş"; kyori=1.1 ; jikan=2}; 
{kiten="ÈÓÅÄ¶¶"; shuten="¸å³Ú±à"; keiyu="ÆîËÌÀş"; kyori=1.4 ; jikan=2}; 
{kiten="¸å³Ú±à"; shuten="ÅìÂçÁ°"; keiyu="ÆîËÌÀş"; kyori=1.3 ; jikan=3}; 
{kiten="ÅìÂçÁ°"; shuten="ËÜ¶ğ¹ş"; keiyu="ÆîËÌÀş"; kyori=0.9 ; jikan=2}; 
{kiten="ËÜ¶ğ¹ş"; shuten="¶ğ¹ş"; keiyu="ÆîËÌÀş"; kyori=1.4; jikan=2}; 
{kiten="¶ğ¹ş"; shuten="À¾¥ö¸¶"; keiyu="ÆîËÌÀş"; kyori=1.4; jikan=2}; 
{kiten="À¾¥ö¸¶"; shuten="²¦»Ò"; keiyu="ÆîËÌÀş"; kyori=1.0; jikan=2}; 
{kiten="²¦»Ò"; shuten="²¦»Ò¿ÀÃ«"; keiyu="ÆîËÌÀş"; kyori=1.2; jikan=2}; 
{kiten="²¦»Ò¿ÀÃ«"; shuten="»ÖÌĞ"; keiyu="ÆîËÌÀş"; kyori=1.6; jikan=3}; 
{kiten="»ÖÌĞ"; shuten="ÀÖ±©´äÊ¥"; keiyu="ÆîËÌÀş"; kyori=1.1; jikan=2}; 
{kiten="À¾Á¥¶¶" ; shuten="¸¶ÌÚÃæ»³"; keiyu="ÅìÀ¾Àş"; kyori=1.9; jikan=3}; 
{kiten="¸¶ÌÚÃæ»³"; shuten="Ì¯Åµ"; keiyu="ÅìÀ¾Àş"; kyori=2.1 ; jikan=2}; 
{kiten="Ì¯Åµ"; shuten="¹ÔÆÁ"; keiyu="ÅìÀ¾Àş"; kyori=1.3 ; jikan=2}; 
{kiten="¹ÔÆÁ"; shuten="Æî¹ÔÆÁ"; keiyu="ÅìÀ¾Àş"; kyori=1.5 ; jikan=2}; 
{kiten="Æî¹ÔÆÁ"; shuten="±º°Â" ; keiyu="ÅìÀ¾Àş"; kyori=1.2 ; jikan=2}; 
{kiten="±º°Â" ; shuten="³ëÀ¾"; keiyu="ÅìÀ¾Àş"; kyori=1.9 ; jikan=2}; 
{kiten="³ëÀ¾"; shuten="À¾³ëÀ¾"; keiyu="ÅìÀ¾Àş"; kyori=1.2 ; jikan=2}; 
{kiten="À¾³ëÀ¾"; shuten="Æîº½Ä®"; keiyu="ÅìÀ¾Àş"; kyori=2.7 ; jikan=2}; 
{kiten="Æîº½Ä®"; shuten="ÅìÍÛÄ®"; keiyu="ÅìÀ¾Àş"; kyori=1.2 ; jikan=2}; 
{kiten="ÅìÍÛÄ®"; shuten="ÌÚ¾ì" ; keiyu="ÅìÀ¾Àş"; kyori=0.9 ; jikan=1}; 
{kiten="ÌÚ¾ì"; shuten="ÌçÁ°ÃçÄ®"; keiyu="ÅìÀ¾Àş"; kyori=1.1 ; jikan=1}; 
{kiten="ÌçÁ°ÃçÄ®"; shuten="³ı¾ìÄ®"; keiyu="ÅìÀ¾Àş"; kyori=1.8 ; jikan=2}; 
{kiten="³ı¾ìÄ®"; shuten="ÆüËÜ¶¶"; keiyu="ÅìÀ¾Àş"; kyori=0.5 ; jikan=1}; 
{kiten="ÆüËÜ¶¶"; shuten="Âç¼êÄ®"; keiyu="ÅìÀ¾Àş"; kyori=0.8 ; jikan=1}; 
{kiten="Âç¼êÄ®"; shuten="Ãİ¶¶"; keiyu="ÅìÀ¾Àş"; kyori=1.0; jikan=2}; 
{kiten="Ãİ¶¶"; shuten="¶åÃÊ²¼"; keiyu="ÅìÀ¾Àş"; kyori=1.0; jikan=1}; 
{kiten="¶åÃÊ²¼"; shuten="ÈÓÅÄ¶¶"; keiyu="ÅìÀ¾Àş"; kyori=0.7; jikan=1}; 
{kiten="ÈÓÅÄ¶¶"; shuten="¿À³Úºä"; keiyu="ÅìÀ¾Àş"; kyori=1.2; jikan=2}; 
{kiten="¿À³Úºä"; shuten="Áá°ğÅÄ"; keiyu="ÅìÀ¾Àş"; kyori=1.2; jikan=2}; 
{kiten="Áá°ğÅÄ"; shuten="¹âÅÄÇÏ¾ì"; keiyu="ÅìÀ¾Àş"; kyori=1.7; jikan=3}; 
{kiten="¹âÅÄÇÏ¾ì"; shuten="Íî¹ç"; keiyu="ÅìÀ¾Àş"; kyori=1.9; jikan=3}; 
{kiten="Íî¹ç"; shuten="ÃæÌî"; keiyu="ÅìÀ¾Àş"; kyori=2.0; jikan=3}; 
{kiten="¿·ÌÚ¾ì"; shuten="Ã¤Ì¦"; keiyu="Í­³ÚÄ®Àş"; kyori=1.5; jikan=2}; 
{kiten="Ã¤Ì¦"; shuten="Ë­½§"; keiyu="Í­³ÚÄ®Àş"; kyori=1.7; jikan=2}; 
{kiten="Ë­½§"; shuten="·îÅç"; keiyu="Í­³ÚÄ®Àş"; kyori=1.4; jikan=2}; 
{kiten="·îÅç"; shuten="¿·ÉÙÄ®"; keiyu="Í­³ÚÄ®Àş"; kyori=1.3; jikan=2}; 
{kiten="¿·ÉÙÄ®"; shuten="¶äºÂ°ìÃúÌÜ"; keiyu="Í­³ÚÄ®Àş"; kyori=0.7; jikan=1}; 
{kiten="¶äºÂ°ìÃúÌÜ"; shuten="Í­³ÚÄ®"; keiyu="Í­³ÚÄ®Àş"; kyori=0.5; jikan=1}; 
{kiten="Í­³ÚÄ®"; shuten="ºùÅÄÌç"; keiyu="Í­³ÚÄ®Àş"; kyori=1.0; jikan=1}; 
{kiten="ºùÅÄÌç"; shuten="±ÊÅÄÄ®"; keiyu="Í­³ÚÄ®Àş"; kyori=0.9; jikan=2}; 
{kiten="±ÊÅÄÄ®"; shuten="¹íÄ®"; keiyu="Í­³ÚÄ®Àş"; kyori=0.9; jikan=1}; 
{kiten="¹íÄ®"; shuten="»Ô¥öÃ«"; keiyu="Í­³ÚÄ®Àş"; kyori=0.9; jikan=1}; 
{kiten="»Ô¥öÃ«"; shuten="ÈÓÅÄ¶¶"; keiyu="Í­³ÚÄ®Àş"; kyori=1.1; jikan=2}; 
{kiten="ÈÓÅÄ¶¶"; shuten="¹¾¸ÍÀî¶¶"; keiyu="Í­³ÚÄ®Àş"; kyori=1.6; jikan=3}; 
{kiten="¹¾¸ÍÀî¶¶"; shuten="¸î¹ñ»û"; keiyu="Í­³ÚÄ®Àş"; kyori=1.3; jikan=2}; 
{kiten="¸î¹ñ»û"; shuten="ÅìÃÓÂŞ"; keiyu="Í­³ÚÄ®Àş"; kyori=1.1; jikan=2}; 
{kiten="ÅìÃÓÂŞ"; shuten="ÃÓÂŞ"; keiyu="Í­³ÚÄ®Àş"; kyori=2.0; jikan=2}; 
{kiten="ÃÓÂŞ"; shuten="Í×Ä®"; keiyu="Í­³ÚÄ®Àş"; kyori=1.2; jikan=2}; 
{kiten="Í×Ä®"; shuten="ÀéÀî"; keiyu="Í­³ÚÄ®Àş"; kyori=1.0; jikan=1}; 
{kiten="ÀéÀî"; shuten="¾®Ãİ¸ş¸¶"; keiyu="Í­³ÚÄ®Àş"; kyori=1.0; jikan=2}; 
{kiten="¾®Ãİ¸ş¸¶"; shuten="É¹ÀîÂæ"; keiyu="Í­³ÚÄ®Àş"; kyori=1.5; jikan=2}; 
{kiten="É¹ÀîÂæ"; shuten="Ê¿ÏÂÂæ"; keiyu="Í­³ÚÄ®Àş"; kyori=1.4; jikan=2}; 
{kiten="Ê¿ÏÂÂæ"; shuten="±ÄÃÄÀÖÄÍ"; keiyu="Í­³ÚÄ®Àş"; kyori=1.8; jikan=2}; 
{kiten="±ÄÃÄÀÖÄÍ"; shuten="±ÄÃÄÀ®Áı"; keiyu="Í­³ÚÄ®Àş"; kyori=1.5; jikan=2}; 
{kiten="±ÄÃÄÀ®Áı"; shuten="ÏÂ¸÷»Ô"; keiyu="Í­³ÚÄ®Àş"; kyori=2.1; jikan=3}; 
] 
