(* 12 À±ºÂ¤òÉ½¤¹·¿ *) 
type seiza_t = Capricorus	(* »³ÍÓºÂ *) 
             | Aquarius		(* ¿åÉÓºÂ *) 
             | Pisces		(* µûºÂ *) 
             | Aries		(* ²´ÍÓºÂ *) 
             | Taurus		(* ²´µíºÂ *) 
             | Gemini		(* ÁÐ»ÒºÂ *) 
             | Cancer		(* ³ªºÂ *) 
             | Leo		(* »â»ÒºÂ *) 
             | Virgo		(* ²µ½÷ºÂ *) 
             | Libra		(* Å·ÇéºÂ *) 
             | Scorpius		(* ê¸ºÂ *) 
             | Sagittarius	(* ¼Í¼êºÂ *) 
